// Code generated by mockery v2.33.2. DO NOT EDIT.

package provisioningpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeProvisioningServiceServer is an autogenerated mock type for the UnsafeProvisioningServiceServer type
type MockUnsafeProvisioningServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedProvisioningServiceServer provides a mock function with given fields:
func (_m *MockUnsafeProvisioningServiceServer) mustEmbedUnimplementedProvisioningServiceServer() {
	_m.Called()
}

// NewMockUnsafeProvisioningServiceServer creates a new instance of MockUnsafeProvisioningServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeProvisioningServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeProvisioningServiceServer {
	mock := &MockUnsafeProvisioningServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
