// Code generated by mockery v2.33.2. DO NOT EDIT.

package provisioningpb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockProvisioningServiceClient is an autogenerated mock type for the ProvisioningServiceClient type
type MockProvisioningServiceClient struct {
	mock.Mock
}

// SayHello provides a mock function with given fields: ctx, in, opts
func (_m *MockProvisioningServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *SayHelloResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *SayHelloRequest, ...grpc.CallOption) (*SayHelloResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *SayHelloRequest, ...grpc.CallOption) *SayHelloResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SayHelloResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *SayHelloRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockProvisioningServiceClient creates a new instance of MockProvisioningServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvisioningServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvisioningServiceClient {
	mock := &MockProvisioningServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
